/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bi.assignment;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;

import javax.imageio.ImageIO;

import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;
import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import ru.yandex.qatools.ashot.shooting.ShootingStrategies;



public class App {
   
   public static ChromeDriver createDriver() {
     //TODO Create a new chrome Driver and Return the same
        WebDriverManager.chromedriver().setup();
        ChromeDriver driver;
        driver = new ChromeDriver();
        return driver;
   }

   public static void printQKartLoadingtime(ChromeDriver driver){
       //TODO Navigate to home page of QKart and verify the time taken for the page to load
        long start = TimeUnit.MILLISECONDS.toSeconds(System.currentTimeMillis());
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");
        long end = TimeUnit.MILLISECONDS.toSeconds(System.currentTimeMillis());
	    long elapsedTime = end - start;
        System.out.println("Time taken to load Qkart page : " + elapsedTime + " seconds");

   }

//    public static void captureFullPageScreenshot(ChromeDriver driver){
//        //TODO: Capture the full page screenshot
//        //Save the file with a unique name
//        // Print the path of the file
//         driver.get("https://crio-qkart-frontend-qa.vercel.app/");
//         // String time = String.valueOf(java.time.LocalDateTime.now());
//         // String timestamp = time.replace(':', '/');
//         String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
//         Screenshot screenshot = new AShot()
// 				.shootingStrategy(ShootingStrategies.viewportPasting(100))
//                 .takeScreenshot(driver);
// 		try {
// 			ImageIO.write(screenshot.getImage(), "PNG", new File("FullPageScreenshot" + timeStamp +".png"));
// 		} catch (IOException e) {

// 			e.printStackTrace();
// 		}

//    }

   public static void GetProductImageandURL(ChromeDriver driver, String productName) throws InterruptedException{
       //TODO: Given the product name, print the price of the project and the url of the image
       driver.get("https://crio-qkart-frontend-qa.vercel.app/");
       Thread.sleep(2000);
       driver.findElement(By.xpath("//p[text()='"+productName+"']"));
       System.out.println("Price of " +productName+ ": " + driver.findElement(By.xpath("//p[text()='"+productName+"']/following-sibling::p")).getText());
       System.out.println("Image URL of" +productName+ ": " + driver.findElement(By.xpath("//p[text()='"+productName+"']/parent::div/preceding-sibling::img")).getAttribute("src") );
   }

   public static void main(String[] args) {
        ChromeDriver driver = createDriver();
        String input = String.join(" ", args );
        try{

            printQKartLoadingtime(driver);

            //captureFullPageScreenshot(driver);
          
            GetProductImageandURL(driver,input );
          
        }catch(Exception e)
        {
           System.out.println(e.getMessage());
        }finally{
            driver.quit();
        }
   }
}
